plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id 'maven-publish'
}

base {
    archivesName = project.archives_base_name
}
group = project.maven_group

def env = System.getenv()

version = project.mod_version
if(env.COMMIT_HASH != null) {
    version += "+${env.COMMIT_HASH}"
}

repositories {
    maven { url = "https://maven.nucleoid.xyz/" }
    maven { url = "https://maven.gegy.dev/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation "xyz.nucleoid:plasmid:${project.plasmid_version}"
}

processResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

fabricApi {
    configureDataGeneration() {
        modId = "uhc-datagen"
        createSourceSet = true
        client = true
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        if (env.MAVEN_URL) {
            maven {
                credentials {
                    username env.MAVEN_USERNAME
                    password env.MAVEN_PASSWORD
                }
                url env.MAVEN_URL
            }
        } else {
            mavenLocal()
        }
    }
}