# Automatically builds and publishes the mod when a new release is created on GitHub.
# It uploads the mod to GitHub, CurseForge and Modrinth.

name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Read mod version from Gradle
        id: read_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mod_version'

      - name: Generate data files
        run: ./gradlew clean runDatagen

      - name: Build with Gradle
        run: ./gradlew build -Pversion=${{ github.event.release.tag_name }}

      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_ACTIONS: true
          SNAPSHOT: false
          MINOR_VERSION: ${{ github.event.release.tag_name }}
          MODRINTH: ${{ secrets.MODRINTH_KEY }}
          CHANGELOG: ${{ github.event.release.body }}

      - name: Publish mod to GitHub, CurseForge and Modrinth
        id: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          changelog: ${{ github.event.release.body }}
          java: 21

          modrinth-featured: false

      - name: Add job summary
        run: |
          echo "# Results" >> $GITHUB_STEP_SUMMARY
          echo "- [CurseForge Link](${{ steps.publish.outputs.curseforge-url }})" >> $GITHUB_STEP_SUMMARY
          echo "- [Modrinth Link](${{ steps.publish.outputs.modrinth-url }})" >> $GITHUB_STEP_SUMMARY
          echo "- [GitHub Link](${{ steps.publish.outputs.github-url }})" >> $GITHUB_STEP_SUMMARY
          echo "# Changelog" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.event.release.body }}" >> $GITHUB_STEP_SUMMARY